/**
 * Centralized route paths. Use these instead of string literals for navigation and links.
 */
export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SETTINGS: '/settings',
  TENANTS: '/tenants',
  TENANTS_NEW: '/tenants/new',
  CUSTOMERS: '/customers',
  STAFF: '/staff',
  STAFF_NEW: '/staff/new',
  STAFF_EDIT: (id: string) => `/staff/${id}`,
  PROMOTIONS: '/promotions',
  PROMOTIONS_NEW: '/promotions/new',
  PROMOTIONS_SIMULATOR: '/promotions/simulator',
  PROMOTIONS_DETAIL: (id: string) => `/promotions/${id}`,
  FOLLOWUPS: '/followups',
  REPORTS: '/reports',
  RETENTION: '/retention',
  PROFESSIONALS: '/professionals',
  SERVICES: '/services',
  APPOINTMENTS: '/appointments',
  CRON_JOBS: '/admin/cron-jobs',
  STORE_CARTS: '/store/carts',
  STORE_ORDERS: '/store/orders',
  STORE_PRODUCTS: '/store/products',
  STORE_CATEGORIES: '/store/categories',
  WHATSAPP: '/whatsapp',
  WHATSAPP_WIZARD: '/whatsapp/wizard',
  WHATSAPP_TRIGGERS: '/whatsapp/triggers',
  WHATSAPP_TRIGGER_EDIT: (id: string) => `/whatsapp/triggers/${id}`,
  WHATSAPP_MENU: (id: string) => `/whatsapp/menus/${id}`,
  WHATSAPP_CONFIG: '/whatsapp/config',
  WHATSAPP_WORKFLOWS: '/whatsapp/workflows',
  WHATSAPP_BOT: '/whatsapp/bot',
  AI: '/ai',
  AI_APPOINTMENTS: '/ai/appointments',
} as const
